import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// A single autogenerated sidebar: order + labels come from each doc's frontmatter (sidebar_position / title).
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
